import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import logo from '@/app/assets/img/logo.svg';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'SAuth',
    description: 'Generated by SAuth team',
    icons: {
        icon: [{ url: '/assets/img/logo.png' }],
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
